name: Build and Deploy

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static export
        run: npm run build

      - name: Configure Git user
        run: |
          git config --global user.email "sh.nawrose@gmail.com"
          git config --global user.name "Shah Nawrose"

      - name: Deploy to GitHub Pages
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d out --repo https://x-access-token:${PAT}@github.com/shahnawroz/10ms_Assesment.git
