name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Recommended LTS version
          cache: 'npm'      # Adds caching for faster builds

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Verify output
        run: |
          ls -la out/
          [ -d out ] || exit 1  # Explicitly check out directory exists

      - name: Configure Git
        run: |
          git config --global user.email "sh.nawrose@gmail.com"
          git config --global user.name "Shah Nawrose"
          git config --global init.defaultBranch main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # More reliable than npx gh-pages
        with:
          github_token: ${{ secrets.GH_TOKEN }}  # Use default token
          publish_dir: ./out
          force_orphan: true  # Ensures clean deployment