name: Build and Deploy

on:
  push:
    branches:
      - main  # your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js static export
        run: npm run build  # this will generate the 'out' directory because of output: export in next.config.js

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx gh-pages -d out --repo https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shahnawroz/10ms_Assesment.git
